# Sponsoring this effort

Thank you for your interesting in sponsoring the effort to write the book "Building Effective LLM-based applications with Semantic Kernel". 
Below you can find the options to sponsor my work.

github: [wmeints]
ko_fi: willemmeints
